Repository googleapis/google-cloud-python-happybase, pull requests merged in 2018-10, with the labels that each got.

#41 Prep 0.30.2 release.
  CHANGELOG.md
  setup.py
Labels: cla: yes

#47 Garden changelog.
  CHANGELOG.md
Labels: cla: yes

#48 Prepare happybase-0.31.0 release.
  CHANGELOG.md
  setup.py
Labels: cla: yes, packaging, type: process

#49 Testing cleanups
  src/google/cloud/happybase/batch.py
  src/google/cloud/happybase/connection.py
  src/google/cloud/happybase/table.py
  tox.ini
  unit_tests/test_batch.py
  unit_tests/test_connection.py
  unit_tests/test_pool.py
  unit_tests/test_table.py
Labels: cla: yes, testing

#50 Removing instance.copy() and timeout parameter from constructor.
  src/google/cloud/happybase/connection.py
  unit_tests/test_connection.py
  unit_tests/test_pool.py
Labels: cla: yes
