Repository googleapis/google-cloud-python-happybase, pull requests merged in 2018-12, with the labels that each got.

#54 Using mutate_rows() instead of row.commit()
  src/google/cloud/happybase/batch.py
  unit_tests/test_batch.py
Labels: cla: yes

#57 Pool: fix call to '_get_instance'.
  src/google/cloud/happybase/pool.py
  unit_tests/test_pool.py
Labels: cla: yes, release blocking, type: bug

#56 Release google-cloud-python-happybase 0.32.0
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes, status: blocked
